// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5GMTkAAOywU7rUUWsCzM-mVlrghTw5YM',
    appId: '1:201921166974:web:6df4de5220ab3b8f4ce22f',
    messagingSenderId: '201921166974',
    projectId: 'fir-flutter-codelab-92a42',
    authDomain: 'fir-flutter-codelab-92a42.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-92a42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLyAqG3iKBxYqDalwz39t1SmXVc31bkAI',
    appId: '1:201921166974:android:35a3fe773ea833414ce22f',
    messagingSenderId: '201921166974',
    projectId: 'fir-flutter-codelab-92a42',
    storageBucket: 'fir-flutter-codelab-92a42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClcbq5A86m0pte6xOfSKzX6ttNNFIT1JU',
    appId: '1:201921166974:ios:49e1a4c93b396d774ce22f',
    messagingSenderId: '201921166974',
    projectId: 'fir-flutter-codelab-92a42',
    storageBucket: 'fir-flutter-codelab-92a42.appspot.com',
    iosClientId: '201921166974-e4lgnfati3cpsvbu4720l81djqho00p0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClcbq5A86m0pte6xOfSKzX6ttNNFIT1JU',
    appId: '1:201921166974:ios:49e1a4c93b396d774ce22f',
    messagingSenderId: '201921166974',
    projectId: 'fir-flutter-codelab-92a42',
    storageBucket: 'fir-flutter-codelab-92a42.appspot.com',
    iosClientId: '201921166974-e4lgnfati3cpsvbu4720l81djqho00p0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
